apiVersion: v1
kind: Service
metadata:
  name: data-bicicletas-service
  namespace: twcam
spec:
  selector:
    app: data-bicicletas-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: data-polucion-service
  namespace: twcam
spec:
  selector:
    app: data-polucion-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
---
# Ayuntamiento Data Service Deployment Configuration
apiVersion: v1
kind: Service
metadata:
  name: data-ayuntamiento-service
  namespace: twcam
spec:
  selector:
    app: data-ayuntamiento-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: ClusterIP
