version: '3.8'

services:
  database-bicicletas:
    image: mysql:8.0
    container_name: mysql-bicicletas
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # Cambia esta contrase침a por una m치s segura
      MYSQL_USER: marcorodas # Nombre del nuevo usuario
      MYSQL_PASSWORD: 1234 # Contrase침a del nuevo usuario
      MYSQL_DATABASE: bicicletas # Nombre de tu base de datos
    volumes:
      - ./MRDS_DataBases/db_bicicletas.sql:/docker-entrypoint-initdb.d/db_bicicletas.sql # Volumen para el archivo de inicializaci칩n
      - mysql_data:/var/lib/mysql # Volumen persistente para los datos de la base de datos
    networks:
      - mrds_network
    ports:
      - "3308:3306" # Exponer el puerto de MySQL

  mongodb:
    image: mongo:6.0
    container_name: mongo-bicicletas
    restart: unless-stopped
    volumes:
      - ./MRDS_DataBases/mdb_bicicletas.js:/docker-entrypoint-initdb.d/mdb_bicicletas.js:ro
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mrds_network


networks:
  mrds_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local # Utiliza un volumen persistente local
  mongo_data:
    driver: local # Utiliza un volumen persistente local
