#Bicicletas
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-bicicletas
  namespace: twcam
spec:
  clusterIP: None
  selector:
    app: mongo-bicicletas
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo

#Polución
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-polucion
  namespace: twcam
spec:
  clusterIP: None
  selector:
    app: mongo-polucion
  ports:
    - port: 27018
      targetPort: 27017  
      name: mongo

# Ayuntamiento
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-ayuntamiento
  namespace: twcam
spec:
  clusterIP: None
  selector:
    app: mongo-ayuntamiento
  ports:
    - port: 27019
      targetPort: 27017  # También 27017 en el contenedor
      name: mongo

