---
# StatefulSet para MySQL (bicicletas y polucion)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: twcam
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      # MySQL Bicicletas
        - name: mysql-bicicletas
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_PASSWORD
            - name: MYSQL_TCP_PORT
              value: "3308"   
          command:
            - "mysqld"
            - "--port=3308"
          ports:
          - containerPort: 3308
            name: mysql-bicicletas-port  
          volumeMounts:
            - name: mysql-bicicletas-pvc
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/db_bicicletas.sql
              subPath: db_bicicletas.sql
      # MySQL Polución
        - name: mysql-polucion
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_PASSWORD
            - name: MYSQL_TCP_PORT
              value: "3309"   
          command:
            - "mysqld"
            - "--port=3309"
          ports:
          - containerPort: 3309
            name: mysql-polucion-port
          volumeMounts:
            - name: mysql-polucion-pvc
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/db_polucion.sql
              subPath: db_polucion.sql
      volumes:
        - name: init-scripts
          configMap:
            name: init-scripts-configmap
  volumeClaimTemplates:
    - metadata:
        name: mysql-bicicletas-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
    - metadata:
        name: mysql-polucion-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi