# Bicicletas MySQL StatefulSet Configuration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-bicicletas
  namespace: twcam
spec:
  serviceName: "mysql-bicicletas"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-bicicletas
  template:
    metadata:
      labels:
        app: mysql-bicicletas
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 27:27 /var/lib/mysql"]
          volumeMounts:
            - name: mysql-bicicletas-pvc
              mountPath: /var/lib/mysql
          securityContext:
            runAsUser: 0
      containers:
        - name: mysql
          image: mysql/mysql-server:8.0.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: bicicletas 
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-bicicletas-pvc
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/db_bicicletas.sql
              subPath: db_bicicletas.sql
      volumes:
        - name: init-scripts
          configMap:
            name: init-scripts-configmap
  volumeClaimTemplates:
    - metadata:
        name: mysql-bicicletas-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
        storageClassName: manual
        selector:
          matchLabels:
            app: mysql
            tipo: bicicletas
---
# Polución MySQL StatefulSet Configuration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-polucion
  namespace: twcam
spec:
  serviceName: "mysql-polucion"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-polucion
  template:
    metadata:
      labels:
        app: mysql-polucion
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 27:27 /var/lib/mysql"]
          volumeMounts:
            - name: mysql-polucion-pvc
              mountPath: /var/lib/mysql
          securityContext:
            runAsUser: 0
      containers:
        - name: mysql
          image: mysql/mysql-server:8.0.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-polucion-pvc
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/db_polucion.sql
              subPath: db_polucion.sql
      volumes:
        - name: init-scripts
          configMap:
            name: init-scripts-configmap
  volumeClaimTemplates:
    - metadata:
        name: mysql-polucion-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
        storageClassName: manual
        selector:
          matchLabels:
            app: mysql
            tipo: polucion
