apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicicletas-service
  namespace: twcam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bicicletas-service
  template:
    metadata:
      labels:
        app: bicicletas-service
    spec:
      containers:
        - name: bicicletas
          image: rodasmarco/bicicletas-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: APP_NAME_BICICLETAS
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SERVER_PORT_BICICLETAS
            - name: DATA_BICICLETAS_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: DATA_BICICLETAS_URL
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: AUTH_URL
            - name: SPRINGDOC_API_DOCS_PATH
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SPRINGDOC_API_DOCS_PATH_BICICLETAS
            - name: SPRINGDOC_SWAGGER_UI_PATH
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SPRINGDOC_SWAGGER_UI_PATH_BICICLETAS
            - name: SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER

---
#Auth Service Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: twcam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: rodasmarco/auth-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
            - name: SYS_TOKEN_ISSUER
              value: TWCAM
            - name: SYS_TOKEN_KEY
              value: MySuperSecureEncriptedAndProtectedKey
            - name: SPRINGDOC_API_DOCS_PATH
              value: /api/v1/auth/api-spec
            - name: SPRINGDOC_SWAGGER_UI_PATH
              value: /api/v1/auth/api-gui.html
            - name: SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER
              value: method

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polucion-service
  namespace: twcam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polucion-service
  template:
    metadata:
      labels:
        app: polucion-service
    spec:
      containers:
        - name: polucion
          image: rodasmarco/polucion-service:latest
          ports:
            - containerPort: 8091
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: APP_NAME_POLUCION
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SERVER_PORT_POLUCION
            - name: DATA_POLUCION_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: DATA_POLUCION_URL
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: AUTH_URL
            - name: SPRINGDOC_API_DOCS_PATH
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SPRINGDOC_API_DOCS_PATH_POLUCION
            - name: SPRINGDOC_SWAGGER_UI_PATH
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SPRINGDOC_SWAGGER_UI_PATH_POLUCION
            - name: SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayuntamiento-service
  namespace: twcam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ayuntamiento-service
  template:
    metadata:
      labels:
        app: ayuntamiento-service
    spec:
      containers:
        - name: ayuntamiento
          image: rodasmarco/ayuntamiento-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: APP_NAME_AYUNTAMIENTO
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: APP_NAME_AYUNTAMIENTO
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SERVER_PORT_AYUNTAMIENTO
            - name: DATA_BICICLETAS_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: DATA_BICICLETAS_URL
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: AUTH_URL
            - name: BICICLETAS_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: BICICLETAS_URL
            - name: POLUCION_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: POLUCION_URL
            - name: DATA_POLUCION_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: DATA_POLUCION_URL
            - name: DATA_AYUNTAMIENTO_URL
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: DATA_AYUNTAMIENTO_URL
            - name: SYSTEM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twcam-secrets
                  key: SYSTEM_TOKEN
            - name: SPRINGDOC_API_DOCS_PATH
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SPRINGDOC_API_DOCS_PATH_AYUNTAMIENTO
            - name: SPRINGDOC_SWAGGER_UI_PATH
              valueFrom:
                configMapKeyRef:
                  name: twcam-config
                  key: SPRINGDOC_SWAGGER_UI_PATH_AYUNTAMIENTO