apiVersion: v1
kind: ConfigMap
metadata:
  name: twcam-config
  namespace: twcam
data:
  APP_NAME_BICICLETAS: bicicletas-service
  SERVER_PORT_BICICLETAS: "8084"
  DATA_BICICLETAS_URL: http://data-bicicletas-service:8083/api/v1/data/bicicletas

  APP_NAME_POLUCION: polucion-service
  SERVER_PORT_POLUCION: "8091"
  DATA_POLUCION_URL: http://data-polucion-service:8086/api/v1/data-polucion

  APP_NAME_AYUNTAMIENTO: ayuntamiento-service
  SERVER_PORT_AYUNTAMIENTO: "8090"
  BICICLETAS_URL: http://bicicletas-service:8084/api/v1/bicicletas
  POLUCION_URL: http://polucion-service:8091/api/v1/polucion
  DATA_AYUNTAMIENTO_URL: http://data-ayuntamiento-service:8087/api/v1/data/ayuntamiento

  AUTH_URL: http://auth-service:8085/api/v1/auth/authorize

  SPRINGDOC_API_DOCS_PATH_BICICLETAS: /api/v1/documentation/api-spec
  SPRINGDOC_SWAGGER_UI_PATH_BICICLETAS: /api/v1/documentation/api-gui.html

  SPRINGDOC_API_DOCS_PATH_POLUCION: /api/v1/polucion/api-spec
  SPRINGDOC_SWAGGER_UI_PATH_POLUCION: /api/v1/polucion/api-gui.html

  SPRINGDOC_API_DOCS_PATH_AYUNTAMIENTO: /api/v1/documentation/api-spec
  SPRINGDOC_SWAGGER_UI_PATH_AYUNTAMIENTO: /api/v1/documentation/api-gui.html

  SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER: method

  SERVER_PORT_AUTH: "8085"
  SYS_TOKEN_ISSUER: TWCAM
  SYS_TOKEN_KEY: MySuperSecureEncriptedAndProtectedKey

